// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoRDIGOZb-TXdaTEovW3coJl9Pl8SAqj8',
    appId: '1:921277221310:web:1a136b881eec4f3a5d91ef',
    messagingSenderId: '921277221310',
    projectId: 'icgc-app-b4822',
    authDomain: 'icgc-app-b4822.firebaseapp.com',
    databaseURL: 'https://icgc-app-b4822-default-rtdb.firebaseio.com',
    storageBucket: 'icgc-app-b4822.appspot.com',
    measurementId: 'G-DRGE182ZKE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9ElXgMdpIBoMROUukkUodUMWYKEOQyeo',
    appId: '1:921277221310:android:f844b3f3559705285d91ef',
    messagingSenderId: '921277221310',
    projectId: 'icgc-app-b4822',
    databaseURL: 'https://icgc-app-b4822-default-rtdb.firebaseio.com',
    storageBucket: 'icgc-app-b4822.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbE4fjurgUtOzRDCGFwXgcFJEiw4PAvsw',
    appId: '1:921277221310:ios:6a43451c022b8f615d91ef',
    messagingSenderId: '921277221310',
    projectId: 'icgc-app-b4822',
    databaseURL: 'https://icgc-app-b4822-default-rtdb.firebaseio.com',
    storageBucket: 'icgc-app-b4822.appspot.com',
    iosClientId: '921277221310-pfpcidgfl0tlnaiqigc461b8kar234c4.apps.googleusercontent.com',
    iosBundleId: 'com.example.churchApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbE4fjurgUtOzRDCGFwXgcFJEiw4PAvsw',
    appId: '1:921277221310:ios:6a43451c022b8f615d91ef',
    messagingSenderId: '921277221310',
    projectId: 'icgc-app-b4822',
    databaseURL: 'https://icgc-app-b4822-default-rtdb.firebaseio.com',
    storageBucket: 'icgc-app-b4822.appspot.com',
    iosClientId: '921277221310-pfpcidgfl0tlnaiqigc461b8kar234c4.apps.googleusercontent.com',
    iosBundleId: 'com.example.churchApp',
  );
}
